import os
from enum import Enum

# --- Core Paths ---
# The absolute path to the root of the application.
APP_ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
# The directory where assets like icons and .set files are stored.
ASSETS_DIR = os.path.join(APP_ROOT_DIR, "assets")

# --- Asset File Paths ---
APP_ICON = os.path.join(ASSETS_DIR, "logo.ico")
REPOS_SET = os.path.join(ASSETS_DIR, "repos.set")
LAUNCHER_EXECUTABLE = os.path.join(APP_ROOT_DIR, "bin", "Launcher.exe")
RELEASE_GROUPS_SET = os.path.join(ASSETS_DIR, "release_groups.set")
FOLDER_EXCLUDE_SET = os.path.join(ASSETS_DIR, "folder_exclude.set")
EXCLUDE_EXE_SET = os.path.join(ASSETS_DIR, "exclude_exe.set")
DEMOTED_SET = os.path.join(ASSETS_DIR, "demoted.set")
FOLDER_DEMOTED_SET = os.path.join(ASSETS_DIR, "folder_demoted.set")
KILLPROCS_SET = os.path.join(ASSETS_DIR, "killprocs.set")
OPTIONS_ARGUMENTS_SET = os.path.join(ASSETS_DIR, "options_arguments.set")
GOVERNED_EXECUTABLES_SET = os.path.join(ASSETS_DIR, "governed_executables.set")

# --- Data/Cache File Paths ---
# These files are generated by the application and stored in the root directory.
STEAM_JSON_FILE = os.path.join(APP_ROOT_DIR, "steam.json")
STEAM_FILTERED_TXT = "steam_filtered.txt"
NORMALIZED_INDEX_CACHE = "normalized_steam_games.cache"

# --- Editor Column Indices ---
class EditorCols(Enum):
    INCLUDE = 0
    NAME = 1
    DIRECTORY = 2
    STEAMID = 3
    NAME_OVERRIDE = 4
    OPTIONS = 5
    ARGUMENTS = 6
    RUN_AS_ADMIN = 7
    CM_PATH = 8
    CM_OPTIONS = 9
    CM_ARGUMENTS = 10
    CM_RUN_WAIT = 11
    BW_PATH = 12
    BW_OPTIONS = 13
    BW_ARGUMENTS = 14
    BW_RUN_WAIT = 15
    MM_PATH = 16
    MM_OPTIONS = 17
    MM_ARGUMENTS = 18
    MM_RUN_WAIT = 19
    HIDE_TASKBAR = 20
    MM_GAME_PROFILE = 21
    MM_DESKTOP_PROFILE = 22
    PLAYER1_PROFILE = 23
    PLAYER2_PROFILE = 24
    MEDIACENTER_PROFILE = 25
    JA_PATH = 26
    JA_OPTIONS = 27
    JA_ARGUMENTS = 28
    JA_RUN_WAIT = 29
    JB_PATH = 30
    JB_OPTIONS = 31
    JB_ARGUMENTS = 32
    JB_RUN_WAIT = 33
    PRE1_PATH = 34
    PRE1_OPTIONS = 35
    PRE1_ARGUMENTS = 36
    PRE1_RUN_WAIT = 37
    POST1_PATH = 38
    POST1_OPTIONS = 39
    POST1_ARGUMENTS = 40
    POST1_RUN_WAIT = 41
    PRE2_PATH = 42
    PRE2_OPTIONS = 43
    PRE2_ARGUMENTS = 44
    PRE2_RUN_WAIT = 45
    POST2_PATH = 46
    POST2_OPTIONS = 47
    POST2_ARGUMENTS = 48
    POST2_RUN_WAIT = 49
    PRE3_PATH = 50
    PRE3_OPTIONS = 51
    PRE3_ARGUMENTS = 52
    PRE3_RUN_WAIT = 53
    POST3_PATH = 54
    POST3_OPTIONS = 55
    POST3_ARGUMENTS = 56
    POST3_RUN_WAIT = 57
    KILL_LIST = 58
    LAUNCHER_EXE = 59
    LAUNCHER_EXE_OPTIONS = 60
    LAUNCHER_EXE_ARGUMENTS = 61
    EXEC_ORDER = 62
    TERM_ORDER = 63
    ISO_PATH = 64
    DM_PATH = 65
    DM_OPTIONS = 66
    DM_ARGUMENTS = 67
    DM_RUN_WAIT = 68
    DM_MOUNT_CFG = 69
    DM_UNMOUNT_CFG = 70
    AUDIO_APP_PATH = 71
    AUDIO_APP_OPTIONS = 72
    AUDIO_APP_ARGUMENTS = 73
    AUDIO_APP_RUN_WAIT = 74
    RUN_AUDIO_CONFIG = 75
    RETURN_AUDIO_CONFIG = 76
    UNBORDER_CONFIG = 77
    REBORDER_CONFIG = 78
