import os
from enum import Enum

# --- Core Paths ---
# The absolute path to the root of the application.
APP_ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
# The directory where assets like icons and .set files are stored.
ASSETS_DIR = os.path.join(APP_ROOT_DIR, "assets")

# --- Asset File Paths ---
APP_ICON = os.path.join(ASSETS_DIR, "logo.ico")
REPOS_SET = os.path.join(ASSETS_DIR, "repos.set")
LAUNCHER_EXECUTABLE = os.path.join(APP_ROOT_DIR, "bin", "Launcher.exe")
RELEASE_GROUPS_SET = os.path.join(ASSETS_DIR, "release_groups.set")
FOLDER_EXCLUDE_SET = os.path.join(ASSETS_DIR, "folder_exclude.set")
EXCLUDE_EXE_SET = os.path.join(ASSETS_DIR, "exclude_exe.set")
DEMOTED_SET = os.path.join(ASSETS_DIR, "demoted.set")
FOLDER_DEMOTED_SET = os.path.join(ASSETS_DIR, "folder_demoted.set")
KILLPROCS_SET = os.path.join(ASSETS_DIR, "killprocs.set")
OPTIONS_ARGUMENTS_SET = os.path.join(ASSETS_DIR, "options_arguments.set")
GOVERNED_EXECUTABLES_SET = os.path.join(ASSETS_DIR, "governed_executables.set")

# --- Data/Cache File Paths ---
# These files are generated by the application and stored in the root directory.
STEAM_JSON_FILE = os.path.join(APP_ROOT_DIR, "steam.json")
STEAM_FILTERED_TXT = "steam_filtered.txt"
NORMALIZED_INDEX_CACHE = "normalized_steam_games.cache"

# --- Editor Column Indices ---
class EditorCols(Enum):
    INCLUDE = 0
    NAME = 1
    DIRECTORY = 2
    STEAMID = 3
    NAME_OVERRIDE = 4
    OPTIONS = 5
    ARGUMENTS = 6
    RUN_AS_ADMIN = 7
    CM_PATH = 8
    CM_OPTIONS = 9
    CM_ARGUMENTS = 10
    CM_RUN_WAIT = 11
    BW_PATH = 12
    BW_OPTIONS = 13
    BW_ARGUMENTS = 14
    BW_RUN_WAIT = 15
    UNBORDER_CFG = 16
    UNBORDER_CFG_OPTIONS = 17
    UNBORDER_CFG_ARGUMENTS = 18
    REBORDER_CFG = 19
    REBORDER_CFG_OPTIONS = 20
    REBORDER_CFG_ARGUMENTS = 21
    MM_GAME_PROFILE = 22
    MM_GAME_PROFILE_OPTIONS = 23
    MM_GAME_PROFILE_ARGUMENTS = 24
    MM_DESKTOP_PROFILE = 25
    MM_DESKTOP_PROFILE_OPTIONS = 26
    MM_DESKTOP_PROFILE_ARGUMENTS = 27
    PLAYER1_PROFILE = 28
    PLAYER1_PROFILE_OPTIONS = 29
    PLAYER1_PROFILE_ARGUMENTS = 30
    PLAYER2_PROFILE = 31
    PLAYER2_PROFILE_OPTIONS = 32
    PLAYER2_PROFILE_ARGUMENTS = 33
    MEDIACENTER_PROFILE = 34
    MEDIACENTER_PROFILE_OPTIONS = 35
    MEDIACENTER_PROFILE_ARGUMENTS = 36
    JA_PATH = 37
    JA_OPTIONS = 38
    JA_ARGUMENTS = 39
    JA_RUN_WAIT = 40
    JB_PATH = 41
    JB_OPTIONS = 42
    JB_ARGUMENTS = 43
    JB_RUN_WAIT = 44
    PRE1_PATH = 45
    PRE1_OPTIONS = 46
    PRE1_ARGUMENTS = 47
    PRE1_RUN_WAIT = 48
    POST1_PATH = 49
    POST1_OPTIONS = 50
    POST1_ARGUMENTS = 51
    POST1_RUN_WAIT = 52
    PRE2_PATH = 53
    PRE2_OPTIONS = 54
    PRE2_ARGUMENTS = 55
    PRE2_RUN_WAIT = 56
    POST2_PATH = 57
    POST2_OPTIONS = 58
    POST2_ARGUMENTS = 59
    POST2_RUN_WAIT = 60
    PRE3_PATH = 61
    PRE3_OPTIONS = 62
    PRE3_ARGUMENTS = 63
    PRE3_RUN_WAIT = 64
    POST3_PATH = 65
    POST3_OPTIONS = 66
    POST3_ARGUMENTS = 67
    POST3_RUN_WAIT = 68
    KILL_LIST = 69
    LAUNCHER_EXE = 70
    LAUNCHER_EXE_OPTIONS = 71
    LAUNCHER_EXE_ARGUMENTS = 72
    EXEC_ORDER = 73
    TERM_ORDER = 74
    ISO_PATH = 75
    DM_PATH = 76
    DM_OPTIONS = 77
    DM_ARGUMENTS = 78
    DM_RUN_WAIT = 79
    DM_MOUNT_CFG = 80
    DM_MOUNT_CFG_OPTIONS = 81
    DM_MOUNT_CFG_ARGUMENTS = 82
    DM_UNMOUNT_CFG = 83
    DM_UNMOUNT_CFG_OPTIONS = 84
    DM_UNMOUNT_CFG_ARGUMENTS = 85
    AUDIO_APP_PATH = 86
    AUDIO_APP_OPTIONS = 87
    AUDIO_APP_ARGUMENTS = 88
    AUDIO_APP_RUN_WAIT = 89
    AUDIO_GAME_CFG = 90
    AUDIO_GAME_CFG_OPTIONS = 91
    AUDIO_GAME_CFG_ARGUMENTS = 92
    AUDIO_MEDIACENTER_CFG = 93
    AUDIO_MEDIACENTER_CFG_OPTIONS = 94
    AUDIO_MEDIACENTER_CFG_ARGUMENTS = 95
    HIDE_TASKBAR = 96
